export const getInitialMunicipios = () => ([
  { nombre: 'Santa Bárbara', ref: 1 },
  { nombre: 'Arada', ref: 1 },
  { nombre: 'Atima', ref: 1 },
  { nombre: 'Azacualpa', ref: 1 },
  { nombre: 'Ceguaca', ref: 1 },
  { nombre: 'Chinda', ref: 1 },
  { nombre: 'Concepción del Norte', ref: 1 },
  { nombre: 'Concepción del Sur', ref: 1 },
  { nombre: 'El Níspero', ref: 1 },
  { nombre: 'Gualala', ref: 1 },
  { nombre: 'Ilama', ref: 1 },
  { nombre: 'Las Vegas', ref: 1 },
  { nombre: 'Macuelizo', ref: 1 },
  { nombre: 'Naranjito', ref: 1 },
  { nombre: 'Nueva Frontera', ref: 1 },
  { nombre: 'Nuevo Celilac', ref: 1 },
  { nombre: 'Petoa', ref: 1 },
  { nombre: 'Protección', ref: 1 },
  { nombre: 'Quimistán', ref: 1 },
  { nombre: 'San Francisco de Ojuera', ref: 1 },
  { nombre: 'San José de las Colinas', ref: 1 },
  { nombre: 'San Luis', ref: 1 },
  { nombre: 'San Marcos', ref: 1 },
  { nombre: 'San Nicolás', ref: 1 },
  { nombre: 'San Pedro Zacapa', ref: 1 },
  { nombre: 'Santa Rita', ref: 1 },
  { nombre: 'San Vicente Centenario', ref: 1 },
  { nombre: 'Trinidad', ref: 1 },

  { nombre: "Santa Rosa de Copán", ref: 2 },
  { nombre: "Cabañas", ref: 2 },
  { nombre: "Concepción", ref: 2 },
  { nombre: "Copán Ruinas", ref: 2 },
  { nombre: "Corquin", ref: 2 },
  { nombre: "Cucuyagua", ref: 2 },
  { nombre: "Dolores", ref: 2 },
  { nombre: "Dulce Nombre", ref: 2 },
  { nombre: "El Paraiso", ref: 2 },
  { nombre: "Florida", ref: 2 },
  { nombre: "La Jigua", ref: 2 },
  { nombre: "La Unión", ref: 2 },
  { nombre: "Nueva Arcadia", ref: 2 },
  { nombre: "San Agustin", ref: 2 },
  { nombre: "San Antonio", ref: 2 },
  { nombre: "San Jerónimo", ref: 2 },
  { nombre: "San José", ref: 2 },
  { nombre: "San Juan de Opoa", ref: 2 },
  { nombre: "San Nicolás", ref: 2 },
  { nombre: "San Pedro de Copán", ref: 2 },
  { nombre: "Santa Rita", ref: 2 },
  { nombre: "Trinidad de Copán", ref: 2 },
  { nombre: "Veracruz", ref: 2 },

  { nombre: 'Gracias', ref: 3 },
  { nombre: 'Belén', ref: 3 },
  { nombre: 'Candelaria', ref: 3 },
  { nombre: 'Cololaca', ref: 3 },
  { nombre: 'Erandique', ref: 3 },
  { nombre: 'Gualcince', ref: 3 },
  { nombre: 'Guarita', ref: 3 },
  { nombre: 'La Campa', ref: 3 },
  { nombre: 'La Iguala', ref: 3 },
  { nombre: 'La Unión', ref: 3 },
  { nombre: 'La Virtud', ref: 3 },
  { nombre: 'Las Flores', ref: 3 },
  { nombre: 'Lepaera', ref: 3 },
  { nombre: 'Mapulaca', ref: 3 },
  { nombre: 'Piraera', ref: 3 },
  { nombre: 'San Andrés', ref: 3 },
  { nombre: 'San Francisco', ref: 3 },
  { nombre: 'San Juan Guarita', ref: 3 },
  { nombre: 'San Manuel Colohete', ref: 3 },
  { nombre: 'San Marcos de Calquín', ref: 3 },
  { nombre: 'San Rafael', ref: 3 },
  { nombre: 'San Sebastian', ref: 3 },
  { nombre: 'Santa Cruz', ref: 3 },
  { nombre: 'Talgua', ref: 3 },
  { nombre: 'Tambla', ref: 3 },
  { nombre: 'Tomalá', ref: 3 },
  { nombre: 'Valladolid', ref: 3 },
  { nombre: 'Virginia', ref: 3 },

  { nombre: 'Ocotepeque', ref: 4 },
  { nombre: 'Belén Gualcho', ref: 4 },
  { nombre: 'Concepción', ref: 4 },
  { nombre: 'Dolores Merendón', ref: 4 },
  { nombre: 'Fraternidad', ref: 4 },
  { nombre: 'La Encarnación', ref: 4 },
  { nombre: 'La Labor', ref: 4 },
  { nombre: 'Lucerna', ref: 4 },
  { nombre: 'Mercedes', ref: 4 },
  { nombre: 'San Fernando', ref: 4 },
  { nombre: 'San Francisco del Valle', ref: 4 },
  { nombre: 'San Jorge', ref: 4 },
  { nombre: 'San Marcos', ref: 4 },
  { nombre: 'Santa Fé', ref: 4 },
  { nombre: 'Sensenti', ref: 4 },
  { nombre: 'Sinuapa', ref: 4 }
])


export const getInitialUnidadesTecnicas = () => ([
  { nombre: 'Dirección General de Normalización', ref: 1 },
  { nombre: 'Unidad de Vigilancia de la Salud', ref: 1 },
  { nombre: 'Programa Ampliado de Inmunización PAI', ref: 1 },
  { nombre: 'Unidad de Comunicación Institucional', ref: 1 },
  { nombre: 'Comité de Control Interno Institucional', ref: 1 },
  { nombre: 'Unidad Administradora de Fondos de Cooperación Externa UAFCE', ref: 1 },
  { nombre: 'Unidad de Licitaciones', ref: 1 },
  { nombre: 'Bienes Nacionales', ref: 1 },
  { nombre: 'Primer Nivel de Atención', ref: 1 },
  { nombre: 'Segundo Nivel de Atención', ref: 1 },
  { nombre: 'Unidad de Transparencia', ref: 1 },
  { nombre: 'Subsecretaria de Redes Integradas de Servicio de Salud', ref: 1 },
  { nombre: 'Unidad de Logistica de Medicamentos e Insumos', ref: 1 },
  { nombre: 'Dirección General de Vigilancia del Marco Normativo', ref: 1 },
  { nombre: 'Unidad de Gestión de la Información', ref: 1 },
  { nombre: 'Unidad de Planeamiento y Evaluacion de la Gestión', ref: 1 },

  { nombre: 'Archivo Institucional', ref: 2 },
  { nombre: 'Comité de Ética', ref: 2 },
  { nombre: 'USINIEH', ref: 2 },
  { nombre: 'COCOIN', ref: 2 },
  { nombre: 'Comunicaciones', ref: 2 },
  { nombre: 'Construcciones', ref: 2 },
  { nombre: 'UPEG', ref: 2 },
  { nombre: 'Adquisiciones', ref: 2 },
  { nombre: 'Desarrollo Organizacional', ref: 2 },
  { nombre: 'Servicios Educativos', ref: 2 },
  { nombre: 'Talento Humano', ref: 2 },
  { nombre: 'Curriculo y Evaluación', ref: 2 },
  { nombre: 'Tecnología Educativa', ref: 2 },
  { nombre: 'CREAH', ref: 2 },
  { nombre: 'UCIENG', ref: 2 },
  { nombre: 'Género en Educación', ref: 2 },
  { nombre: 'PROHECO', ref: 2 },
  { nombre: 'Editorial Sabio Valle', ref: 2 },
  { nombre: 'Portal de Transparencia', ref: 2 },
  { nombre: 'APRODE', ref: 2 },
  { nombre: 'CESS-SICA/CELAC', ref: 2 },
])


export const getInitialImagenes = () => ([
  { nombre: 'Nosotros', fileId: null, enlace: null},
  { nombre: 'Representante', fileId: null, enlace: null},
  { nombre: 'Organigrama', fileId: null, enlace: null},
  { nombre: 'Valores', fileId: null, enlace: null}
])

export const getInitialHomeInfo = () => ([
  { nombre: 'Nosotros', fileId: null, enlace: null},
  { nombre: 'Representante', fileId: null, enlace: null},
  { nombre: 'Organigrama', fileId: null, enlace: null},
  { nombre: 'Valores', fileId: null, enlace: null}
])

export const getInitialRedianBoards = () => ([
  { 
    nombre: 'GDSS. ADASBA, Santa Bárbara', 
    enlace: 'https://public.tableau.com/views/TableroAINC-ADASBA_17109748214510/Tablero?:language=es-ES&publish=yes&:sid=&:display_count=n&:origin=viz_share_link', 
    ref: 1
  },
  { 
    nombre: 'GDSS. Municipalidad de Macuelizo, Santa Bárbara', 
    enlace: 'https://public.tableau.com/views/IndicadoresAINC-Macuelizo__16783726937320/DASH-Macuelizo?:language=es-ES&:sid=&:display_count=n&:origin=viz_share_link', 
    ref: 1
  },
  { 
    nombre: 'GDSS. El Jaral, Santa Rita, Copán', 
    enlace: 'https://public.tableau.com/views/TableroAINC-ADASBA_17109748214510/Tablero?:language=es-ES&publish=yes&:sid=&:display_count=n&:origin=viz_share_link', 
    ref: 2
  },
  { 
    nombre: 'GDSS. Municipalidad de Gracias, Lempira', 
    enlace: 'https://public.tableau.com/views/TableroAINC-Gracias_16941102002800/Tablero?:language=es-ES&:sid=&:display_count=n&:origin=viz_share_link', 
    ref: 3
  },
  { 
    nombre: 'GDSS. Municipalidad de Lepaera, Lempira', 
    enlace: 'https://public.tableau.com/views/TableroAINC-Lepaera_17181507162960/DASH-Frecuencia?:language=es-ES&:sid=&:display_count=n&:origin=viz_share_link', 
    ref: 3
  },
  { 
    nombre: 'GDSS. Municipalidad de Belén Gualcho, Ocotepeque', 
    enlace: 'https://public.tableau.com/views/TableroAINC-BelenGualcho1/T-Analisis?:language=es-ES&:sid=&:display_count=n&:origin=viz_share_link', 
    ref: 4
  },
])